CREATE TYPE "RedirectSource" AS ENUM ('ADMIN_DESTINATION', 'PRESET_CONTROLLED');

ALTER TABLE "User" ADD COLUMN "discordWebhookUrl" TEXT;

ALTER TABLE "Link" ADD COLUMN "redirectSource" "RedirectSource" NOT NULL DEFAULT 'ADMIN_DESTINATION';
